-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 11:15:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `Password` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `first_name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `last_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `Name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attribute` (
  `Name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `category_name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`Name`),
  INDEX `fk_attribute_category1_idx` (`category_name` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_category1`
    FOREIGN KEY (`category_name`)
    REFERENCES `mydb`.`category` (`Name`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `last_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `Age` INT NOT NULL,
  `Experience` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Address` VARCHAR(45) COLLATE 'utf8mb3_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `Password` VARCHAR(20) COLLATE 'utf8mb3_bin' NOT NULL,
  `City` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `first_name` VARCHAR(30) CHARACTER SET 'utf8mb3' NOT NULL,
  `last_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `Email` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Activated` TINYINT NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Description` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Level` INT NOT NULL,
  `Duration` INT NOT NULL,
  `Kontakt` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `instructor_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `category_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_program_user_idx` (`Username` ASC) VISIBLE,
  INDEX `fk_program_category1_idx` (`category_name` ASC) VISIBLE,
  INDEX `fk_program_instructor_idx` (`instructor_id` ASC) VISIBLE,
  INDEX `fk_program_location_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_category1`
    FOREIGN KEY (`category_name`)
    REFERENCES `mydb`.`category` (`Name`),
  CONSTRAINT `fk_program_instructor`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `mydb`.`instructor` (`Id`),
  CONSTRAINT `fk_program_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`Id`),
  CONSTRAINT `fk_program_user`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`user` (`Username`))
ENGINE = InnoDB
AUTO_INCREMENT = 15;


-- -----------------------------------------------------
-- Table `mydb`.`attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attribute_value` (
  `program_id` INT NOT NULL,
  `attribute_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `Value` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`program_id`, `attribute_name`),
  INDEX `fk_program_has_attribute_attribute1_idx` (`attribute_name` ASC) VISIBLE,
  INDEX `fk_program_has_attribute_program1_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_has_attribute_attribute1`
    FOREIGN KEY (`attribute_name`)
    REFERENCES `mydb`.`attribute` (`Name`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_program_has_attribute_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`program` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL,
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avatar_user1_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_avatar_user1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`user` (`Username`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `mydb`.`diary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diary` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_diary_user1_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_diary_user1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`user` (`Username`))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `mydb`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`day` (
  `Date` DATE NOT NULL,
  `excersise_type` VARCHAR(45) COLLATE 'utf8mb3_bin' NULL DEFAULT NULL,
  `Duration` INT NULL DEFAULT NULL,
  `Intensity` INT NULL DEFAULT NULL,
  `Result` INT NULL DEFAULT NULL,
  `Weight` DOUBLE NULL DEFAULT NULL,
  `diary_id` INT NOT NULL,
  PRIMARY KEY (`Date`, `diary_id`),
  INDEX `fk_diary_id1_idx` (`diary_id` ASC) VISIBLE,
  CONSTRAINT `fk_diary_id1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `mydb`.`diary` (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL,
  `Seen` TINYINT NOT NULL,
  `date_time` DATE NOT NULL,
  `sender_name` VARCHAR(30) CHARACTER SET 'utf8mb3' NOT NULL,
  `receiver_name` VARCHAR(30) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_message_user1_idx` (`sender_name` ASC) VISIBLE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender_name`)
    REFERENCES `mydb`.`user` (`Username`))
ENGINE = InnoDB
AUTO_INCREMENT = 12;


-- -----------------------------------------------------
-- Table `mydb`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`picture` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL,
  `program_id` INT NOT NULL,
  `cover` TINYINT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_picture_program1_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_picture_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`program` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL,
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `program_id` INT NOT NULL,
  PRIMARY KEY (`Id`, `program_id`, `Username`),
  INDEX `fk_question_program1_idx` (`program_id` ASC) VISIBLE,
  INDEX `fk_question_user1` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_question_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`program` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`user` (`Username`))
ENGINE = InnoDB
AUTO_INCREMENT = 8;


-- -----------------------------------------------------
-- Table `mydb`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reply` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL,
  `question_id` INT NOT NULL,
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_reply_user1_idx` (`Username` ASC) VISIBLE,
  INDEX `fk_reply_question1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_reply_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_reply_user1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`user` (`Username`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `mydb`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscription` (
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `category_name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Username`, `category_name`),
  INDEX `fk_user_has_category_category1_idx` (`category_name` ASC) VISIBLE,
  INDEX `fk_user_has_category_user1_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_category_category1`
    FOREIGN KEY (`category_name`)
    REFERENCES `mydb`.`category` (`Name`),
  CONSTRAINT `fk_user_has_category_user1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`user` (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`support` (
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `Password` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `first_name` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `last_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_programs` (
  `Username` VARCHAR(30) COLLATE 'utf8mb3_bin' NOT NULL,
  `program_id` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Payment` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`Username`, `program_id`),
  INDEX `fk_user_has_program_program1_idx` (`program_id` ASC) VISIBLE,
  INDEX `fk_user_has_program_user1_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_program_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`program` (`Id`),
  CONSTRAINT `fk_user_has_program_user1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`user` (`Username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
